title: Conference Deadlines
description: Countdowns to top SE/NLP/ML/PL conference deadlines
author: yttty

domain: "yttty.github.io"
baseurl: "https://yttty.github.io/conf-deadlines"

github_username: yttty
github_repo: conf-deadliness

markdown: kramdown

include: ["_pages"]
